### PR TITLE
Fixes for S3 attachments

### LINKED ISSUE #103: Cannot migrate MRs with attachments
Even after setting up an S3 bucket, trying to migrate a MR that has an attachment gives the following error:
```
Could not download attachment FILENAME.png
Error: params.Body is required
    at ManagedUpload.validateBody (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/s3/managed_upload.js:271:13)
    at ManagedUpload.configure (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/s3/managed_upload.js:123:10)
    at new ManagedUpload (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/s3/managed_upload.js:95:10)
    at features.constructor.upload (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/services/s3.js:1383:20)
    at Response.<anonymous> (/Users/username/Projects/node-gitlab-2-github/src/utils.ts:75:16)
    at Request.<anonymous> (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/request.js:369:18)
    at Request.callListeners (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/request.js:22:10) {
```
And the resulting PR in Github is not created.

Is there a way to still migrate the MR->PR and just not include the attachment?

### LINKED ISSUE #106: The issue file attachment is ignored
I'm migrating issues from GitLab to GitHub and noticed that file attachments like binaries or source code attached to comment/description are ignored. 

For example original issue on GitLab contains following text:

```txt
[attached](/uploads/d31d82da5d7a0753a418f845f30f1968/libSomeLib.dll)
```

The issue created by node-gitlab-2-github contains following text:

```txt
[attached](/uploads/d31d82da5d7a0753a418f845f30f1968/libSomeLib.dll)
```

Images somehow works... well, I did not provide keys for S3. At least I see an error that image cannot be uploaded. The file attachments are just ignored.

### LINKED ISSUE #107: Duplicated attachments in case of throttling
In case if GitHub rejects requests (for example because of  throttling) the script downloads the same attachment and uploads them to S3 many times (depends on how many times script is executed)

The reason is asynchronous nature of the script. The script downloads GitLab tickets, parses them and downloads attachments ahead. The file name for attachment is generated based on some random number generator (rather than checksum). Thus if I run the script many times, it downloads the same file many times and generates new name for the file.

Following is code in the `utils.ts`, which causes this behavior:

```ts
    const id = crypto.randomBytes(16).toString('hex');
    const newFileName = id + basename;
    const relativePath = githubRepoId ? `${githubRepoId}/${newFileName}` : newFileName;
```

### PR DESCRIPTION
**Pull request by mdbenito**
This PR:
* Closes #107: uses a hash of the attachment's URL to avoid duplicates upon failure
* Closes #103: Doesn't fail if there was an error downloading an attachment
* Closes #106: migrates arbitrary attachment types using a browser cookie (workaround for [GitLab's missing API endpoint](https://gitlab.com/gitlab-org/gitlab/-/issues/24155))
* Uses previous attachment URL if S3 is not configured

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -34,7 +34,7 @@ export const generateUserProjectRegex = () => {
 
 // Creates new attachments and replaces old links
 export const migrateAttachments = async (body: string, githubRepoId: number | undefined, s3: S3Settings, gitlabHelper: GitlabHelper) => {
-  const regexp = /!\[([^\]]+)\]\((\/uploads[^)]+)\)/g;
+  const regexp = /(!?)\[([^\]]+)\]\((\/uploads[^)]+)\)/g;
```
Comment (spruce) [inline src/utils.ts:37]: Wouldn't this catch more than Uploads because of the optionality of the prefix?

**Review by spruce — APPROVED** [review]
